package com.eCommerce.eCommerceApp.entity;
//import java.sql.Date;
import java.util.Date;
import java.util.List;
import java.util.TimeZone;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.TemporalType;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Caisse {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idCaisse;
	private float amount;

	@Temporal(TemporalType.TIMESTAMP) 
	private Date creationDate;// the date when the caisse is added
    private Date operationDate;// the date when the operation was done by the company
	private String type;// a Revenu(+) or a Depense(-)
    private String Origin; // office, Product, campaign
	private String involvedParty;	
	private String description;

    @OneToOne
    @JoinColumn(name = "campaign_id")
    private Campaign campaign;

    @OneToOne
    @JoinColumn(name = "product_id")
    private Product product;

    public Caisse() {
        // No need to set the ID here; it will be generated by the database.
		// setting the timeZone to tunisian timeZone
		TimeZone tunisianTimeZone = TimeZone.getTimeZone("Africa/Tunis");
        TimeZone.setDefault(tunisianTimeZone);
    }

	 // Getter and setter methods for 'idCaisse'
	 public Long getIdCaisse() {
        return idCaisse;
    }

    public void setIdCaisse(Long idCaisse) {
        this.idCaisse = idCaisse;
    }

	// Getter and setter methods for 'operationDate'
	 public Date getOperationDate() {
        return operationDate;
    }

    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }

    
	public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    // Getter and setter methods for 'amount'
    public float getAmount() {
        return amount;
    }

    public void setAmount(float amount) {
        this.amount = amount;
    }

    // Getter and setter methods for 'creationDate'
    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    // Getter and setter methods for 'type'
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    // Getter and setter methods for 'involvedParty'
    public String getInvolvedParty() {
        return involvedParty;
    }

    public void setInvolvedParty(String involvedParty) {
        this.involvedParty = involvedParty;
    }

    // Getter and setter methods for 'description'
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Campaign getCampaign() {
        return campaign;
    }

    public void setCampaign(Campaign campaign) {
        this.campaign = campaign;
    }

    public String getOrigin() {
        return Origin;
    }

    public void setOrigin(String origin) {
        Origin = origin;
    }
}
