package com.eCommerce.eCommerceApp.entity;

//import java.sql.Date;
import java.util.Date;
import java.util.List;
import java.util.TimeZone;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Company {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idCompany;
    private String companyName;
    @Temporal(TemporalType.TIMESTAMP)
    private Date creationDate;
    private Boolean isActive;

    @OneToMany(mappedBy = "company", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnore
    private List<Product> products;


    public Company() {
        // No need to set the ID here; it will be generated by the database.
        // setting the timeZone to tunisian timeZone
        TimeZone tunisianTimeZone = TimeZone.getTimeZone("Africa/Tunis");
        TimeZone.setDefault(tunisianTimeZone);
    }

    // Getter and setter methods for 'companyName'
    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public Long getIdCompany() {
        return idCompany;
    }

     public Boolean getIsActive() {
        return isActive;
    }

    
    public List<Product> getProducts() {
        return products;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    // Getter and setter methods for 'creationDate'
    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

}
